/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Add type declaration for the @env module
declare module '@env' {
  export const API_BASE_URL: string;
  // Add other environment variables here if needed
  // export const ANOTHER_VARIABLE: string;
}